[http]
port = 3000

[mqtt]
topics = ["topic"]
broker = "localhost"
port = 1883
user = "user"
password = "password"

[camera]
timeout = 10 # milliseconds before the shot is taken

[timelapse]
interval = 10000 # milliseconds
resolution = [1920, 1080]

[device]
name = "Raspberry 1" # device identifier
role = "sensor"      # device role
