[http]
port = 3000

[mqtt]
topics = ["topic","hello"]
broker = "localhost"
port = 1883
user = "user"
password = "password"

[camera]
timeout = 10# milliseconds


[timelapse]
interval = 60000 # ms
resolution = [1920, 1080]


[device]
name = "Raspberry 1" # A device identifier
role = "sensor"
